name: rusle_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - geopandas
  - rasterio
  - rioxarray
  - folium
  - shapely
  - pyproj
  - scikit-learn
  - pip:
      - pykrige
