# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-06-02 16:21:49
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    NI_Contours = "NI_Contours"
    NI_outline_poly_shp_3_ = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\NI_outline_poly.shp"
    rainfall_sampling_points = "rainfall_sampling_points"
    European_Silt_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\K_factor\\EU_Soil_data\\Silt_EU23\\Silt_eu23.tif\\European_Silt_pc"
    NI_outline_poly_shp = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\NI_outline_poly.shp"
    European_Sand_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\K_factor\\EU_Soil_data\\Sand_EU23\\Sand_eu23.tif\\European_Sand_pc"
    NI_outline_poly_shp_5_ = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\NI_outline_poly.shp"
    European_Clay_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\K_factor\\EU_Soil_data\\Clay_EU23\\Clay_eu23.tif\\European_Clay_pc"
    European_Org_Carb_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\K_factor\\EU_Soil_data\\Organic_Carbon\\octop_insp\\European_Org_Carb_pc"
    European_USDA_Soil_Texture = arcpy.Raster("European_USDA_Soil_Texture")
    NI_outline_poly_shp_2_ = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\NI_outline_poly.shp"
    NI_Landcover = arcpy.Raster("NI_Landcover")
    European_P_Factor = arcpy.Raster("European_P_Factor")
    NI_outline_poly_shp_4_ = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\soil_erosion_model_data\\NI_outline_poly.shp"

    # Process: Create TIN (Create TIN) (3d)
    NI_Contours_TIN = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\NI_Contours_TIN"
    with arcpy.EnvManager(extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]", outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        arcpy.ddd.CreateTin(out_tin=NI_Contours_TIN, spatial_reference="PROJCS[\"TM75_Irish_Grid\",GEOGCS[\"GCS_TM75\",DATUM[\"D_TM75\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]", in_features=[[NI_Contours, "HEIGHT", "Hard_Line", "FID"]], constrained_delaunay="DELAUNAY")

    # Process: TIN To Raster (TIN To Raster) (3d)
    NI_DTM_10m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_DTM_10m"
    arcpy.ddd.TinRaster(in_tin=NI_Contours_TIN, out_raster=NI_DTM_10m, data_type="FLOAT", method="LINEAR", sample_distance="OBSERVATIONS", z_factor=1, sample_value=17754)
    NI_DTM_10m = arcpy.Raster(NI_DTM_10m)

    # Process: Extract by Mask (Extract by Mask) (sa)
    NI_DTM_clip = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_DTM_clip"
    Extract_by_Mask = NI_DTM_clip
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_DTM_clip = arcpy.sa.ExtractByMask(in_raster=NI_DTM_10m, in_mask_data=NI_outline_poly_shp_3_, extraction_area="INSIDE", analysis_extent="188744.652401789 310076.991915306 366277.720894265 452942.6875 PROJCS[\"TM65_Irish_Grid\",GEOGCS[\"GCS_TM65\",DATUM[\"D_TM65\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_DTM_clip.save(Extract_by_Mask)


    # Process: Fill (Fill) (sa)
    NI_Fill_DTM = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Fill_DTM"
    Fill = NI_Fill_DTM
    NI_Fill_DTM = arcpy.sa.Fill(in_surface_raster=NI_DTM_clip, z_limit=None)
    NI_Fill_DTM.save(Fill)


    # Process: Flow Direction (Flow Direction) (sa)
    NI_FlowDir_D8 = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_FlowDir_D8"
    Flow_Direction = NI_FlowDir_D8
    Output_drop_raster = ""
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_FlowDir_D8 = arcpy.sa.FlowDirection(in_surface_raster=NI_Fill_DTM, force_flow="NORMAL", out_drop_raster=Output_drop_raster, flow_direction_type="D8")
        NI_FlowDir_D8.save(Flow_Direction)


    # Process: Kriging (2) (Kriging) (sa)
    NI_Annual_Rainfall = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Annual_Rainfall"
    Kriging_2_ = NI_Annual_Rainfall
    Rainfall_VoP = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\Rainfall_VoP"
    with arcpy.EnvManager(extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]", outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_Annual_Rainfall = arcpy.sa.Kriging(in_point_features=rainfall_sampling_points, z_field="RAINFALL", semiVariogram_props="Spherical 545.523810 # # #", cell_size="100", search_radius="VARIABLE 12", out_variance_prediction_raster=Rainfall_VoP)
        NI_Annual_Rainfall.save(Kriging_2_)

        Rainfall_VoP = arcpy.Raster(Rainfall_VoP)

    # Process: Raster Calculator (Raster Calculator) (ia)
    NI_R_Factor_100m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_R_Factor_100m"
    Raster_Calculator = NI_R_Factor_100m
    NI_R_Factor_100m = 38.46 + (3.48 * NI_Annual_Rainfall)
    NI_R_Factor_100m.save(Raster_Calculator)


    # Process: Extract by Mask (6) (Extract by Mask) (sa)
    NI_Silt_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Silt_pc"
    Extract_by_Mask_6_ = NI_Silt_pc
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM75_Irish_Grid",GEOGCS["GCS_TM75",DATUM["D_TM75",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_Silt_pc = arcpy.sa.ExtractByMask(in_raster=European_Silt_pc, in_mask_data=NI_outline_poly_shp, extraction_area="INSIDE", analysis_extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS[\"TM75_Irish_Grid\",GEOGCS[\"GCS_TM75\",DATUM[\"D_TM75\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_Silt_pc.save(Extract_by_Mask_6_)


    # Process: Extract by Mask (5) (Extract by Mask) (sa)
    NI_Sand_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Sand_pc"
    Extract_by_Mask_5_ = NI_Sand_pc
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM75_Irish_Grid",GEOGCS["GCS_TM75",DATUM["D_TM75",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_Sand_pc = arcpy.sa.ExtractByMask(in_raster=European_Sand_pc, in_mask_data=NI_outline_poly_shp_5_, extraction_area="INSIDE", analysis_extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS[\"TM75_Irish_Grid\",GEOGCS[\"GCS_TM75\",DATUM[\"D_TM75\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_Sand_pc.save(Extract_by_Mask_5_)


    # Process: Extract by Mask (7) (Extract by Mask) (sa)
    NI_Clay_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Clay_pc"
    Extract_by_Mask_7_ = NI_Clay_pc
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_Clay_pc = arcpy.sa.ExtractByMask(in_raster=European_Clay_pc, in_mask_data=NI_outline_poly_shp_5_, extraction_area="INSIDE", analysis_extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS[\"TM65_Irish_Grid\",GEOGCS[\"GCS_TM65\",DATUM[\"D_TM65\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_Clay_pc.save(Extract_by_Mask_7_)


    # Process: Raster Calculator (5) (Raster Calculator) (ia)
    Calc_M = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\Calc_M"
    Raster_Calculator_5_ = Calc_M
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        Calc_M = (NI_Silt_pc + NI_Sand_pc) * (100 - NI_Clay_pc) 
        Calc_M.save(Raster_Calculator_5_)


    # Process: Extract by Mask (8) (Extract by Mask) (sa)
    NI_Soil_Org_Carb_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Soil_Org_Carb_pc"
    Extract_by_Mask_8_ = NI_Soil_Org_Carb_pc
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_Soil_Org_Carb_pc = arcpy.sa.ExtractByMask(in_raster=European_Org_Carb_pc, in_mask_data=NI_outline_poly_shp, extraction_area="INSIDE", analysis_extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS[\"TM65_Irish_Grid\",GEOGCS[\"GCS_TM65\",DATUM[\"D_TM65\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_Soil_Org_Carb_pc.save(Extract_by_Mask_8_)


    # Process: Raster Calculator (7) (Raster Calculator) (ia)
    NI_Soil_Org_Mat_pc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_Soil_Org_Mat_pc"
    Raster_Calculator_7_ = NI_Soil_Org_Mat_pc
    NI_Soil_Org_Mat_pc =  NI_Soil_Org_Carb_pc * 1.724
    NI_Soil_Org_Mat_pc.save(Raster_Calculator_7_)


    # Process: Raster Calculator (8) (Raster Calculator) (ia)
    NI_Soil_Org_Mat_pc_1to12_1k = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_Soil_Org_Mat_pc_1to12_1k"
    Raster_Calculator_8_ = NI_Soil_Org_Mat_pc_1to12_1k
    NI_Soil_Org_Mat_pc_1to12_1k = Con(NI_Soil_Org_Mat_pc <= 11, NI_Soil_Org_Mat_pc, 11)
    NI_Soil_Org_Mat_pc_1to12_1k.save(Raster_Calculator_8_)


    # Process: Resample (Resample) (management)
    NI_Soil_Org_Mat_pc_1to12 = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Soil_Org_Mat_pc_1to12"
    arcpy.management.Resample(in_raster=NI_Soil_Org_Mat_pc_1to12_1k, out_raster=NI_Soil_Org_Mat_pc_1to12, cell_size="1000 1000", resampling_type="NEAREST")
    NI_Soil_Org_Mat_pc_1to12 = arcpy.Raster(NI_Soil_Org_Mat_pc_1to12)

    # Process: Reclassify (2) (Reclassify) (sa)
    European_Soil_structure_code = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\European_Soil_structure_code"
    Reclassify_2_ = European_Soil_structure_code
    European_Soil_structure_code = arcpy.sa.Reclassify(in_raster=European_USDA_Soil_Texture, reclass_field="Value", remap="1 4;2 4;3 3;4 4;5 3;6 3;7 1;8 2;9 3;10 1;11 2;12 2", missing_values="DATA")
    European_Soil_structure_code.save(Reclassify_2_)


    # Process: Extract by Mask (4) (Extract by Mask) (sa)
    NI_soil_str_code = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_soil_str_code"
    Extract_by_Mask_4_ = NI_soil_str_code
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_soil_str_code = arcpy.sa.ExtractByMask(in_raster=European_Soil_structure_code, in_mask_data=NI_outline_poly_shp_2_, extraction_area="INSIDE", analysis_extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS[\"TM65_Irish_Grid\",GEOGCS[\"GCS_TM65\",DATUM[\"D_TM65\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_soil_str_code.save(Extract_by_Mask_4_)


    # Process: Reclassify (3) (Reclassify) (sa)
    European_soil_permeability_class = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\European_soil_permeability_class"
    Reclassify_3_ = European_soil_permeability_class
    European_soil_permeability_class = arcpy.sa.Reclassify(in_raster=European_USDA_Soil_Texture, reclass_field="Value", remap="1 6;2 6;3 5;4 5;5 4;6 4;7 3;8 3;9 2;10 1;11 1;12 2", missing_values="DATA")
    European_soil_permeability_class.save(Reclassify_3_)


    # Process: Extract by Mask (9) (Extract by Mask) (sa)
    NI_soil_perm_class = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_soil_perm_class"
    Extract_by_Mask_9_ = NI_soil_perm_class
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM75_Irish_Grid",GEOGCS["GCS_TM75",DATUM["D_TM75",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_soil_perm_class = arcpy.sa.ExtractByMask(in_raster=European_soil_permeability_class, in_mask_data=NI_outline_poly_shp_2_, extraction_area="INSIDE", analysis_extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS[\"TM75_Irish_Grid\",GEOGCS[\"GCS_TM75\",DATUM[\"D_TM75\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_soil_perm_class.save(Extract_by_Mask_9_)


    # Process: Raster Calculator (6) (Raster Calculator) (ia)
    NI_K_Factor_500m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_K_Factor_500m"
    Raster_Calculator_6_ = NI_K_Factor_500m
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM75_Irish_Grid",GEOGCS["GCS_TM75",DATUM["D_TM75",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_K_Factor_500m = ((2.1 * Power(10,-4)) * Power(Calc_M, 1.14) * (12 - NI_Soil_Org_Mat_pc_1to12) + 3.25 * (NI_soil_str_code - 2) + 2.5 * (NI_soil_perm_class - 3)) / 100 * 0.1317
        NI_K_Factor_500m.save(Raster_Calculator_6_)


    # Process: Resample (2) (Resample) (management)
    NI_K_Factor_100m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_K_Factor_100m"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM75_Irish_Grid",GEOGCS["GCS_TM75",DATUM["D_TM75",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        arcpy.management.Resample(in_raster=NI_K_Factor_500m, out_raster=NI_K_Factor_100m, cell_size="100 100", resampling_type="NEAREST")
        NI_K_Factor_100m = arcpy.Raster(NI_K_Factor_100m)

    # Process: Flow Accumulation (Flow Accumulation) (sa)
    NI_FlowAcc = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_FlowAcc"
    Flow_Accumulation = NI_FlowAcc
    NI_FlowAcc = arcpy.sa.FlowAccumulation(in_flow_direction_raster=NI_FlowDir_D8, in_weight_raster="", data_type="INTEGER", flow_direction_type="D8")
    NI_FlowAcc.save(Flow_Accumulation)


    # Process: Slope (Slope) (sa)
    NI_Slope = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_Slope"
    Slope = NI_Slope
    NI_Slope = arcpy.sa.Slope(in_raster=NI_Fill_DTM, output_measurement="PERCENT_RISE", z_factor=1, method="PLANAR", z_unit="METER")
    NI_Slope.save(Slope)


    # Process: Raster Calculator (2) (Raster Calculator) (sa)
    NI_LS_factor_10m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_LS_factor_10m"
    Raster_Calculator_2_ = NI_LS_factor_10m
    NI_LS_factor_10m = ((NI_FlowAcc * 30/22.1)^ 0.5) * (0.065 +0.045 * NI_Slope +0.0065* (NI_Slope * NI_Slope))
    NI_LS_factor_10m.save(Raster_Calculator_2_)


    # Process: Resample (4) (Resample) (management)
    NI_LS_factor_100m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_LS_factor_100m"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM65_Irish_Grid",GEOGCS["GCS_TM65",DATUM["D_TM65",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        arcpy.management.Resample(in_raster=NI_LS_factor_10m, out_raster=NI_LS_factor_100m, cell_size="100 100", resampling_type="BILINEAR")
        NI_LS_factor_100m = arcpy.Raster(NI_LS_factor_100m)

    # Process: Reclassify (Reclassify) (sa)
    NI_C_Factor_10k = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_C_Factor_10k"
    Reclassify = NI_C_Factor_10k
    NI_C_Factor_10k = arcpy.sa.Reclassify(in_raster=NI_Landcover, reclass_field="Value", remap="1 29;2 29;3 2230;4 319;5 319;6 319;7 319;8 1;9 420;10 420;11 1;12 1;13 1;14 1;15 1;16 1;17 1;18 1;19 1;20 1;21 21", missing_values="DATA")
    NI_C_Factor_10k.save(Reclassify)


    # Process: Raster Calculator (3) (Raster Calculator) (sa)
    NI_C_Factor_25m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_C_Factor_25m"
    Raster_Calculator_3_ = NI_C_Factor_25m
    NI_C_Factor_25m =  NI_C_Factor_10k/10000
    NI_C_Factor_25m.save(Raster_Calculator_3_)


    # Process: Resample (3) (Resample) (management)
    NI_C_Factor_100m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_C_Factor_100m"
    arcpy.management.Resample(in_raster=NI_C_Factor_25m, out_raster=NI_C_Factor_100m, cell_size="100 100", resampling_type="BILINEAR")
    NI_C_Factor_100m = arcpy.Raster(NI_C_Factor_100m)

    # Process: Extract by Mask (3) (Extract by Mask) (sa)
    NI_P_Factor_100m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\EGM721_P1.gdb\\NI_P_Factor_100m"
    Extract_by_Mask_3_ = NI_P_Factor_100m
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["TM75_Irish_Grid",GEOGCS["GCS_TM75",DATUM["D_TM75",SPHEROID["Airy_Modified",6377340.189,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",200000.0],PARAMETER["False_Northing",250000.0],PARAMETER["Central_Meridian",-8.0],PARAMETER["Scale_Factor",1.000035],PARAMETER["Latitude_Of_Origin",53.5],UNIT["Meter",1.0]]"):
        NI_P_Factor_100m = arcpy.sa.ExtractByMask(in_raster=European_P_Factor, in_mask_data=NI_outline_poly_shp_4_, extraction_area="INSIDE", analysis_extent="188707.921875 309871.75 366567.8125 452942.6875 PROJCS[\"TM75_Irish_Grid\",GEOGCS[\"GCS_TM75\",DATUM[\"D_TM75\",SPHEROID[\"Airy_Modified\",6377340.189,299.3249646]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",250000.0],PARAMETER[\"Central_Meridian\",-8.0],PARAMETER[\"Scale_Factor\",1.000035],PARAMETER[\"Latitude_Of_Origin\",53.5],UNIT[\"Meter\",1.0]]")
        NI_P_Factor_100m.save(Extract_by_Mask_3_)


    # Process: Raster Calculator (4) (Raster Calculator) (sa)
    NI_Av_Annual_Soil_Loss_100m = "C:\\GIS_Course\\EGM721\\Project_1\\EGM721_P1\\egm721_p1.gdb\\NI_Av_Annual_Soil_Loss_100m"
    Raster_Calculator_4_ = NI_Av_Annual_Soil_Loss_100m
    NI_Av_Annual_Soil_Loss_100m =  NI_R_Factor_100m * NI_K_Factor_100m * NI_LS_factor_100m * NI_C_Factor_100m * NI_P_Factor_100m
    NI_Av_Annual_Soil_Loss_100m.save(Raster_Calculator_4_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\GIS_Course\EGM721\Project_1\EGM721_P1\EGM721_P1.gdb", workspace=r"C:\GIS_Course\EGM721\Project_1\EGM721_P1\EGM721_P1.gdb"):
        Model()
